credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    chad:
      email: cfitz@centralmail.me
      name: Chad
      password: $2b$12$whLpnrx98K5FpXPZb8TBf.9C.tu0tWimRPc3vRW2L9ZRE6YSrERcO
cookie:
  expiry_days: 30
  key: ingestai_signature_key # Must be string
  name: ingestai_cookie_name
preauthorized:
  emails:
